version: '3.8'
services: 
  # Backend API Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kospi-backend
    restart: unless-stopped
    env_file:
      - .env 
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    networks:
      - kospi-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Data Collector (Scheduler)
  collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kospi-collector
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mysql
      - backend 
    command: ["npm", "run", "start:scheduler"]
    volumes:
      - ./logs:/app/logs
    networks:
      - kospi-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: kospi-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kospi-network

volumes:
  mysql_data:
  redis_data:

networks:
  kospi-network:
    driver: bridge 